# Start with a base image containing Java runtime
FROM openjdk:20-jdk

#time zone env haven't tried this yet
ENV TZ=America/New_York
RUN ln -fs /usr/share/zoneinfo/$TZ /etc/localtime 

# Add Maintainer Info
LABEL maintainer="s_bharadwaj140735@fanshaweonline.ca"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080

# The application's jar file
ARG JAR_FILE=casestudy.jar

# Add the application's jar to the container
ADD ${JAR_FILE} casestudy.jar

# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/casestudy.jar"]